package kaliandapet100;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import kaliandapet100.model.Ticket;
import kaliandapet100.model.User;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Rog
 */
public class FormRegister extends javax.swing.JFrame {

    /**
     * Creates new form RegisterSecond
     */
    public FormRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnRegister = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtDob = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        txtPwd = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 169, 139));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(74, 52, 46));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 245));
        jPanel2.setLayout(null);

        btnRegister.setBackground(new java.awt.Color(228, 123, 46));
        btnRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegister);
        btnRegister.setBounds(20, 430, 410, 40);

        jLabel1.setBackground(new java.awt.Color(74, 52, 46));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 249, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Register");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(9, 18, 79, 25);

        jLabel3.setBackground(new java.awt.Color(200, 169, 139));
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(9, 49, 432, 2);

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(18, 465, 130, 0);

        txtEmail.setBackground(new java.awt.Color(245, 232, 212));
        txtEmail.setForeground(new java.awt.Color(74, 52, 46));
        jPanel2.add(txtEmail);
        txtEmail.setBounds(20, 300, 415, 36);

        txtDob.setBackground(new java.awt.Color(245, 232, 212));
        txtDob.setForeground(new java.awt.Color(74, 52, 46));
        txtDob.setToolTipText("");
        jPanel2.add(txtDob);
        txtDob.setBounds(20, 230, 415, 36);

        txtName.setBackground(new java.awt.Color(245, 232, 212));
        txtName.setForeground(new java.awt.Color(74, 52, 46));
        jPanel2.add(txtName);
        txtName.setBounds(20, 90, 415, 36);

        txtUsername.setBackground(new java.awt.Color(245, 232, 212));
        txtUsername.setForeground(new java.awt.Color(74, 52, 46));
        jPanel2.add(txtUsername);
        txtUsername.setBounds(20, 160, 415, 36);

        txtPwd.setBackground(new java.awt.Color(245, 232, 212));
        txtPwd.setForeground(new java.awt.Color(74, 52, 46));
        jPanel2.add(txtPwd);
        txtPwd.setBounds(20, 370, 415, 36);

        jLabel2.setBackground(new java.awt.Color(74, 52, 46));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 249, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create password:");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 340, 157, 25);

        jLabel7.setBackground(new java.awt.Color(74, 52, 46));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 249, 240));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Email");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 270, 50, 25);

        jLabel8.setBackground(new java.awt.Color(74, 52, 46));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 249, 240));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Full name");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 60, 60, 25);

        jLabel9.setBackground(new java.awt.Color(74, 52, 46));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 249, 240));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Username");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel2.add(jLabel9);
        jLabel9.setBounds(20, 130, 60, 25);

        jLabel10.setBackground(new java.awt.Color(74, 52, 46));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 249, 240));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Date of Birth");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 200, 80, 25);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(25, 20, 450, 497);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String fullname = txtName.getText();
        String username = txtUsername.getText();
        String password = new String(txtPwd.getPassword());
        String email = txtEmail.getText();
        String dob = txtDob.getText();
        LocalDate memberSince = LocalDate.now();

        User newUser = new User(fullname, username, password, email, LocalDate.parse(dob), memberSince);

        try (Socket socket = new Socket("localhost", 5000);
             ObjectOutputStream output = new ObjectOutputStream(socket.getOutputStream());
             ObjectInputStream input = new ObjectInputStream(socket.getInputStream())) {

            output.writeObject("REGISTER");
            output.writeObject(newUser);

            String response = (String) input.readObject();
            JOptionPane.showMessageDialog(this, response);

            if (response.startsWith("SUCCESS")) {
                // Return to login form after successful registration
                this.dispose();
                new FormLogin().setVisible(true);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error connecting to server.");
        }
        /*
        // Ambil data dari field input
        String fullName = txtName.getText();
        String username = txtUsername.getText();
        String password = new String(txtPwd.getPassword());
        String email = txtEmail.getText();
        LocalDate dob;

        // Validasi input sederhana
        if (fullName.isEmpty() || username.isEmpty() || password.isEmpty() || email.isEmpty() || txtDob.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields must be filled!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Konversi string DOB ke LocalDate
            dob = LocalDate.parse(txtDob.getText()); // Format harus YYYY-MM-DD
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Invalid Date Format! Use YYYY-MM-DD.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Socket socket = new Socket("localhost", 5000); // Hubungkan ke server
             ObjectOutputStream output = new ObjectOutputStream(socket.getOutputStream());
             ObjectInputStream input = new ObjectInputStream(socket.getInputStream())) {

            // Buat objek User dan kirim ke server
            User newUser = new User(fullName, username, password, email, dob, LocalDate.now());
            output.writeBytes("REGISTRATION:" + newUser);
            output.flush();

            // Terima respons dari server
            String response = (String) input.readObject();
            JOptionPane.showMessageDialog(this, response, "Registration Status", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException | ClassNotFoundException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Failed to connect to the server!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        */
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
