package kaliandapet100;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ConnectException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import kaliandapet100.model.Ticket;
import kaliandapet100.model.User;

/**
 *
 * @author Rog
 */
public class FormLogin extends javax.swing.JFrame {

    Socket clientSocket;
    String username, password;

    /**
     * Creates new form Register
     */
    public FormLogin() {
        initComponents();
        try {
            clientSocket = new Socket("localhost", 6000);

        } catch (Exception ex) {
            Logger.getLogger(FormLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        txtFieldPwd = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnLogin1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(200, 169, 139));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(74, 52, 46));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(255, 249, 240));
        jPanel2.setPreferredSize(new java.awt.Dimension(450, 350));
        jPanel2.setLayout(null);

        btnLogin.setBackground(new java.awt.Color(228, 123, 46));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Register");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin);
        btnLogin.setBounds(125, 300, 200, 30);

        txtFieldPwd.setBackground(new java.awt.Color(245, 232, 212));
        txtFieldPwd.setForeground(new java.awt.Color(74, 52, 46));
        jPanel2.add(txtFieldPwd);
        txtFieldPwd.setBounds(20, 160, 415, 36);

        txtUsername.setBackground(new java.awt.Color(245, 232, 212));
        txtUsername.setForeground(new java.awt.Color(74, 52, 46));
        jPanel2.add(txtUsername);
        txtUsername.setBounds(20, 90, 415, 36);

        jLabel1.setBackground(new java.awt.Color(74, 52, 46));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 249, 240));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Password");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 130, 60, 25);

        jLabel3.setBackground(new java.awt.Color(200, 169, 139));
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(9, 53, 432, 2);

        jLabel4.setBackground(new java.awt.Color(200, 169, 139));
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(9, 276, 432, 2);

        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(18, 318, 130, 0);

        btnLogin1.setBackground(new java.awt.Color(228, 123, 46));
        btnLogin1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin1.setText("Login");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogin1);
        btnLogin1.setBounds(17, 212, 415, 40);

        jLabel7.setBackground(new java.awt.Color(74, 52, 46));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 249, 240));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(" Log In");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(9, 22, 60, 25);

        jLabel2.setBackground(new java.awt.Color(74, 52, 46));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 249, 240));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Username");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 60, 60, 25);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(26, 31, 450, 350);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Navigasi ke form Register
            SwingUtilities.invokeLater(() -> {
            FormRegister registerForm = new FormRegister();
            registerForm.setVisible(true);
            this.dispose(); // Menutup form login saat ini
        });
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        // TODO add your handling code here:
        // Validasi input
        // Validasi input
        String username = txtUsername.getText().trim();
        String password = new String(txtFieldPwd.getText());

        // Validasi field tidak boleh kosong
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            txtUsername.requestFocus();
            return;
        }

        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Password tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            txtFieldPwd.requestFocus();
            return;
        }

        // Tampilkan loading indicator
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));

        try (Socket socket = new Socket("localhost", 5000); ObjectOutputStream output = new ObjectOutputStream(socket.getOutputStream()); ObjectInputStream input = new ObjectInputStream(socket.getInputStream())) {

            // Kirim request login ke server
            output.writeObject("LOGIN");
            output.writeObject(username);
            output.writeObject(password);

            // Terima respons dari server
            String response = (String) input.readObject();

            // Reset cursor
            setCursor(Cursor.getDefaultCursor());

            if (response.startsWith("SUCCESS")) {
                // Login berhasil

                // Opsi 1: buat objek User baru dengan data yang ada
                User loggedInUser = new User();
                loggedInUser.setUsername(username);

                // Opsi 2: ambil data user dengan request tambahan ke server
                // Uncomment kode di bawah jika perlu mengambil data user lengkap dari server
                /*
                output.writeObject("GET_USER_DETAILS");
                output.writeObject(username);
                User loggedInUser = (User) input.readObject();
                 */
                // Tampilkan pesan sambutan
                JOptionPane.showMessageDialog(this,
                        "Welcome, " + username + "!",
                        "Login Successful",
                        JOptionPane.INFORMATION_MESSAGE);

                // Navigasi ke FormMenu
                SwingUtilities.invokeLater(() -> {
                    // Cek constructor FormMenu yang tersedia
                    try {
                        // Opsi 1: jika FormMenu menerima parameter User
                        FormMenu menuForm = new FormMenu(loggedInUser);
                        menuForm.setVisible(true);
                        this.dispose();
                    } catch (NoSuchMethodError e) {
                        // Opsi 2: jika FormMenu tanpa parameter
                        try {
                            FormMenu menuForm = new FormMenu(loggedInUser);
                            menuForm.setVisible(true);
                            this.dispose();
                        } catch (Exception ex) {
                            JOptionPane.showMessageDialog(this,
                                    "Error on menu navigation: " + ex.getMessage(),
                                    "Error",
                                    JOptionPane.ERROR_MESSAGE);
                        }
                    }
                });
            } else {
                // Login gagal
                JOptionPane.showMessageDialog(this,
                        response,
                        "Login Failed!",
                        JOptionPane.ERROR_MESSAGE);

                // Reset password field
                txtFieldPwd.setText("");
                txtFieldPwd.requestFocus();
            }
        } catch (ConnectException ce) {
            setCursor(Cursor.getDefaultCursor());
            JOptionPane.showMessageDialog(this,
                    "Unable to connect ot server. Make sure if the server is running.",
                    "Connection Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            setCursor(Cursor.getDefaultCursor());
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnLogin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtFieldPwd;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
