package kaliandapet100;

import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.Socket;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.util.Locale;
import javax.swing.JOptionPane;
import kaliandapet100.model.Ticket;
import kaliandapet100.model.User;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author ACER
 */
public class FormAddTickets extends javax.swing.JFrame {

    /**
     * Creates new form Checkout
     */
    NumberFormat formatter = NumberFormat.getInstance(Locale.US);
    //String username = "Elifele04";
    //String id = "001";
    //String title = "Bruno Mars Concert";
    //int price = 1000000;
    //int subTotal;
    //int quantity;

    public FormAddTickets() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        id_label = new javax.swing.JLabel();
        labelForm = new javax.swing.JLabel();
        labelQty = new javax.swing.JLabel();
        txtStock = new java.awt.TextField();
        txtID = new java.awt.TextField();
        labelQty1 = new javax.swing.JLabel();
        txtPrice = new java.awt.TextField();
        btnAdd = new javax.swing.JButton();
        labelUsername = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        labelQty2 = new javax.swing.JLabel();
        txtTitle = new java.awt.TextField();
        labelQty3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDesc = new javax.swing.JTextArea();
        txtCreator = new java.awt.TextField();
        labelQty4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(200, 169, 139));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        id_label.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        id_label.setForeground(new java.awt.Color(255, 255, 255));
        id_label.setText("ID : ");
        jPanel1.add(id_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

        labelForm.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelForm.setForeground(new java.awt.Color(255, 255, 255));
        labelForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelForm.setText("Add Ticket");
        labelForm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labelForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 280, -1));

        labelQty.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelQty.setForeground(new java.awt.Color(255, 255, 255));
        labelQty.setText("Stock :");
        jPanel1.add(labelQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        txtStock.setBackground(new java.awt.Color(245, 232, 212));
        txtStock.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtStock.setForeground(new java.awt.Color(74, 52, 46));
        jPanel1.add(txtStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 190, -1));

        txtID.setBackground(new java.awt.Color(245, 232, 212));
        txtID.setEditable(false);
        txtID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtID.setForeground(new java.awt.Color(74, 52, 46));
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 190, -1));

        labelQty1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelQty1.setForeground(new java.awt.Color(255, 255, 255));
        labelQty1.setText("Price :");
        jPanel1.add(labelQty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        txtPrice.setBackground(new java.awt.Color(245, 232, 212));
        txtPrice.setEditable(false);
        txtPrice.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(74, 52, 46));
        jPanel1.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 190, -1));

        btnAdd.setBackground(new java.awt.Color(0, 204, 153));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 249, 240));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 420, 120, 38));

        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUsername.setText("Username");
        jPanel1.add(labelUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 130, -1));

        jButton3.setBackground(new java.awt.Color(255, 51, 51));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 249, 240));
        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 38, 38));

        labelQty2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelQty2.setForeground(new java.awt.Color(255, 255, 255));
        labelQty2.setText("Title :");
        jPanel1.add(labelQty2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        txtTitle.setBackground(new java.awt.Color(245, 232, 212));
        txtTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtTitle.setForeground(new java.awt.Color(74, 52, 46));
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 190, -1));

        labelQty3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelQty3.setForeground(new java.awt.Color(255, 255, 255));
        labelQty3.setText("Description :");
        jPanel1.add(labelQty3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        txtDesc.setColumns(20);
        txtDesc.setRows(5);
        jScrollPane1.setViewportView(txtDesc);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 186, 380, 90));

        txtCreator.setBackground(new java.awt.Color(245, 232, 212));
        txtCreator.setEditable(false);
        txtCreator.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtCreator.setForeground(new java.awt.Color(74, 52, 46));
        jPanel1.add(txtCreator, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 190, -1));

        labelQty4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelQty4.setForeground(new java.awt.Color(255, 255, 255));
        labelQty4.setText("Creator  :");
        jPanel1.add(labelQty4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 660, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String id = txtID.getText();
        String title = txtTitle.getText();
        String desc = txtDesc.getText();
        int stock = Integer.parseInt(txtStock.getText());
        int price = Integer.parseInt(txtPrice.getText());
        String creator = txtCreator.getText();
        
        try (Socket socket = new Socket("localhost", 5000); ObjectOutputStream out = new ObjectOutputStream(socket.getOutputStream()); ObjectInputStream in = new ObjectInputStream(socket.getInputStream())) {

            out.writeObject("ADD_TICKET");

            Ticket newTicket = new Ticket(id, title, desc, price, stock, creator,
                    LocalDate.now(), LocalDate.now());
            out.writeObject(newTicket);

            String response = (String) in.readObject();
            JOptionPane.showMessageDialog(null, response);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        User loggedInUser = new User();
        FormMenu formMenu = new FormMenu(loggedInUser);
        formMenu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAddTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAddTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAddTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAddTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormAddTickets().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel id_label;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelForm;
    private javax.swing.JLabel labelQty;
    private javax.swing.JLabel labelQty1;
    private javax.swing.JLabel labelQty2;
    private javax.swing.JLabel labelQty3;
    private javax.swing.JLabel labelQty4;
    private javax.swing.JLabel labelUsername;
    private java.awt.TextField txtCreator;
    private javax.swing.JTextArea txtDesc;
    private java.awt.TextField txtID;
    private java.awt.TextField txtPrice;
    private java.awt.TextField txtStock;
    private java.awt.TextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
